name: "Mark Release as Draft"
description: "Marks the current release as draft"
inputs:
  reason:
    description: "Reason for marking as draft"
    required: true
    default: "No reason provided"
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      with:
        script: |
          await github.rest.repos.updateRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: context.payload.release.id,
            draft: true
          });

          core.setFailed('Marking release as draft: ${{ inputs.reason }}');